services:
  php:
    build: .
    container_name: crm-php
    networks:
      - crm-net
    volumes:
      - .:/var/www:delegated  

  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - crm-net

networks:
  crm-net:
    external: true  # this need to be added to ansible playbook
