version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-php
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
    networks:
      - backend-net

  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    ports:
      - "8081:80"
    volumes:
      # - .:/var/www  <- only dev, not prod
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - backend-net

networks:
  backend-net:
    external: true  # Falls du ein vordefiniertes Netzwerk z. B. mit Ansible erzeugst
